server:
  port: 8080

spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true                # Enable dynamic routes from Eureka
#          lower-case-service-id: true  # Convert service IDs to lowercase
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                # Enable dynamic routes from Eureka
          lower-case-service-id: true  # Convert service IDs to lowercase


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"       # Expose all actuator endpoints for debugging
  endpoint:
    health:
      show-details: always
# The JWT secret must match auth-service's secret
jwt:
  secret: MySuperSecretKeyForJwtThatShouldBeLongEnough12345