spring:
  application:
      name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

  # H2 Console for testing
  spring.h2.console.enabled: true
  spring.h2.console.path: /h2-console

server:
  port: 8082

jwt:
  secret: MySuperSecretKeyForJwtThatShouldBeLongEnough12345
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/