spring:
  application:
        name: user-service
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/orclpdb.docker.internal
#    username: library
#    password: library123
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    database-platform: org.hibernate.dialect.OracleDialect


  datasource:
    url: jdbc:h2:mem:librarydb    # In-memory H2 database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update   # can be 'create', 'create-drop', 'validate', or 'update'
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always   # Show full health details
  endpoints:
    web:
      exposure:
        include: "*"         # Expose all endpoints

  redis:
    host: localhost   # or your Redis server
    port: 6379
  cache:
    type: redis


resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 2s
