spring:
  application:
        name: user-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb.docker.internal
    username: library
    password: library123
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always   # Show full health details
  endpoints:
    web:
      exposure:
        include: "*"         # Expose all endpoints



